# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qx5M4qyk-X9AxXAoQHfZgGs1K5IUQX_t
"""



import streamlit as st
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

tokenizer = AutoTokenizer.from_pretrained("Softechlb/articles_classification")
model = AutoModelForSequenceClassification.from_pretrained("Softechlb/articles_classification")

st.title('My Classifier')
user_input = st.text_input("Enter your data here", "")
button_clicked = st.button("Predict")
if button_clicked:
    inputs = tokenizer(user_input, padding=True, truncation=True, max_length=512, return_tensors="pt")
    outputs = model(inputs["input_ids"], attention_mask=inputs["attention_mask"])
    predicted_label_index = torch.argmax(outputs.logits).item()
    predicted_label_name = category_names[predicted_label_index]
    st.write(f'Prediction: {predicted_label_name}')

