# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qx5M4qyk-X9AxXAoQHfZgGs1K5IUQX_t
"""



import streamlit as st
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# Load the model and tokenizer
model_name = "Softechlb/articles_classification"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Define the category names
category_names = ["news", "sports", "politics", "business", "health", "entertainment"]

# Set the title of the app
st.title('Categorical Classifier(news,sports,politics,business,health,entertainment)')

# Get the user input
user_input = st.text_input("Enter your data here", "")

# When the predict button is clicked
button_clicked = st.button("Predict")
if button_clicked:
    # Tokenize the input and get the model's output
    inputs = tokenizer(user_input, padding=True, truncation=True, max_length=512, return_tensors="pt")
    outputs = model(**inputs)

    # Get the predicted label
    predicted_label_index = torch.argmax(outputs.logits).item()
    predicted_label_name = category_names[predicted_label_index]

    # Create a container for the prediction
    with st.beta_container():
        st.markdown(f'## Prediction: {predicted_label_name}')
